#!/usr/bin/env bash

kick_install networkmanager network-manager-applet gnome-keyring wireless_tools iw
kick_set_ini /etc/NetworkManager/NetworkManager.conf 'connection' 'ipv6.ip6-privacy' '2'
kick_enable NetworkManager

kick_write /etc/modprobe.d/wlan-led.conf 'options iwlwifi led_mode=3'
kick_write /etc/modprobe.d/i915.conf 'options i915 enable_rc6=1 enable_fbc=1 modeset=1'
kick_write /etc/sysctl.d/laptop_mode.conf 'vm.laptop_mode = 5'
kick_write /etc/sysctl.d/writeback_time.conf 'vm.dirty_writeback_centisecs = 1500'

kick_write /etc/profile.d/shell-timeout.sh \
'TMOUT="$(( 120 ))";
[ -z "$DISPLAY" ] && export TMOUT;
case $( /usr/bin/tty ) in
    /dev/tty[0-9]*) export TMOUT;;
esac'

[[ -f /etc/ssh/sshd_config ]] && \
kick_set /etc/ssh/sshd_config PermitRootLogin prohibit-password ' '

kick_write /etc/udev/rules.d/70-wifi-powersave.rules 'ACTION=="add", SUBSYSTEM=="net", KERNEL=="wlan*" RUN+="/usr/bin/iw dev %k set power_save on"'

kick_write /etc/systemd/logind.conf.d/ignore-keys.conf \
'[Login]
HandlePowerKey=ignore
HandleSuspendKey=ignore
HandleHibernateKey=ignore
HandleLidSwitch=ignore
HandleLidSwitchDocked=ignore'

if [[ -d /etc/X11/xorg.conf.d ]]; then
    kick_install xf86-input-synaptics
    kick_write /etc/X11/xorg.conf.d/50-synaptics.conf \
    'Section "InputClass"
        Identifier "touchpad"
        Driver "synaptics"
        MatchIsTouchpad "on"
        Option "VertScrollDelta"   "-25"
        Option "MaxTapTime"        "0"
        Option "VertEdgeScroll"    "1"
        Option "HorizEdgeScroll"   "1"
    EndSection'
fi
