#!/usr/bin/env bash

do_install alsa-utils
do_install pulseaudio-alsa
do_install pavucontrol
do_install pamixer

do_exec amixer -q sset Master unmute

do_set_option /etc/pulse/daemon.conf flat-volumes no
