#!/usr/bin/env bash

kick_install alsa-utils
kick_install pulseaudio-alsa
kick_install pavucontrol
kick_install pamixer

kick_exec amixer -q sset Master unmute

kick_set /etc/pulse/daemon.conf flat-volumes no
