#!/usr/bin/env bash

kick_install ufw

kick_exec ufw default deny  incoming
kick_exec ufw default allow outgoing
kick_exec ufw logging off

kick_exec ufw allow 22/tcp    # ssh
kick_exec ufw allow 8080/tcp  # kodi
kick_exec ufw allow 17500/tcp # dropbox

kick_exec ufw enable
kick_enable ufw
