#!/usr/bin/env bash

read -re -p "HOSTNAME: " h

kick_exec hostnamectl set-hostname "$h"
kick_exec sed -i "s|127\.0\.0\.1.*|127.0.0.1 localhost $h|g" /etc/hosts
kick_exec sed -i "s|::1.*|::1 localhost $h|g" /etc/hosts
