#!/usr/bin/env bash

[[ $UID == 0 ]] || { printf "%s\n" "run as root"; exit 1; }
. configuration

do_install networkmanager
do_install network-manager-applet
do_write /etc/NetworkManager/dnsmasq.d/cache.conf 'cache-size=1000'
do_set_option_ini /etc/NetworkManager/NetworkManager.conf 'main' 'dns' 'dnsmasq'
do_set_option_ini /etc/NetworkManager/NetworkManager.conf 'connection' 'ipv6.ip6-privacy' '2'
do_enable_service NetworkManager

do_write /etc/modprobe.d/wlan-led.conf 'options iwlwifi led_mode=3'
do_write /etc/modprobe.d/i915.conf 'options i915 enable_rc6=1 enable_fbc=1 modeset=1'
do_write /etc/sysctl.d/laptop_mode.conf 'vm.laptop_mode = 5'
do_write /etc/sysctl.d/writeback_time.conf 'vm.dirty_writeback_centisecs = 1500'

do_write /etc/profile.d/shell-timeout.sh \
'TMOUT="$(( 120 ))";
[ -z "$DISPLAY" ] && export TMOUT;
case $( /usr/bin/tty ) in
    /dev/tty[0-9]*) export TMOUT;;
esac'

do_set_option /etc/ssh/sshd_config PermitRootLogin prohibit-password ' '

do_set_option_ini /etc/systemd/logind.conf Login HandlePowerKey ignore
do_set_option_ini /etc/systemd/logind.conf Login HandleSuspendKey ignore
do_set_option_ini /etc/systemd/logind.conf Login HandleHibernateKey ignore
do_set_option_ini /etc/systemd/logind.conf Login HandleLidSwitch ignore
do_set_option_ini /etc/systemd/logind.conf Login HandleLidSwitchDocked ignore

do_write /etc/X11/xorg.conf.d/20-intel.conf \
'Section "Device"
   Identifier  "Intel Graphics"
   Driver      "intel"
   Option      "AccelMethod"  "uxa"
EndSection'

do_write /etc/X11/xorg.conf.d/50-synaptics.conf \
'Section "InputClass"
    Identifier "touchpad"
    Driver "synaptics"
    MatchIsTouchpad "on"
        Option "VertScrollDelta"   "-25"
        Option "MaxTapTime"        "0"
        Option "VertEdgeScroll"    "1"
        Option "HorizEdgeScroll"   "1"
EndSection'
