#!/usr/bin/env bash

do_write /etc/X11/xorg.conf.d/20-keyboard.conf \
'Section "InputClass"
    Identifier "keyboard"
    MatchIsKeyboard "yes"
    Option "XkbLayout" "de"
    Option "XbkVariant" "nodeadkeys"
EndSection'

do_symlink /usr/share/zoneinfo/Europe/Berlin /etc/localtime

do_exec timedatectl set-ntp true
hwclock --systohc --utc

do_write /etc/vconsole.conf 'KEYMAP=de-latin1-nodeadkeys'
do_write /etc/locale.conf 'LANG=de_DE.UTF-8'
do_write /etc/locale.gen \
'de_DE.UTF-8 UTF-8
en_IE.UTF-8 UTF-8
en_US.UTF-8 UTF-8'
do_exec locale-gen
