#!/usr/bin/env bash

kick_write /etc/X11/xorg.conf.d/20-keyboard.conf \
'Section "InputClass"
    Identifier "keyboard"
    MatchIsKeyboard "yes"
    Option "XkbLayout" "de"
    Option "XbkVariant" "nodeadkeys"
EndSection'

kick_symlink /usr/share/zoneinfo/Europe/Berlin /etc/localtime

kick_exec timedatectl set-ntp true
kick_exec hwclock --systohc --utc

kick_write /etc/vconsole.conf 'KEYMAP=de-latin1-nodeadkeys'
kick_write /etc/locale.conf 'LANG=de_DE.UTF-8'
kick_write /etc/locale.gen \
'de_DE.UTF-8 UTF-8
en_IE.UTF-8 UTF-8
en_US.UTF-8 UTF-8'
kick_exec locale-gen
