#!/usr/bin/env bash

[[ $UID == 0 ]] || { printf "%s\n" "run as root"; exit 1; }
. configuration

do_write /etc/modprobe.d/blacklist.conf \
'blacklist firewire_ohci
blacklist firewire_core
blacklist kvm
blacklist kvm_intel
blacklist xpad
blacklist dell_laptop'
