#!/usr/bin/env bash

kick_set /etc/makepkg.conf 'COMPRESSXZ' '(xz -T 0 -c -z -)'
kick_set /etc/makepkg.conf 'PKGEXT' "\'.pkg.tar\'"

kick_set /etc/pacman.conf 'Color'
kick_set /etc/pacman.conf 'TotalDownload'
kick_set /etc/pacman.conf 'VerbosePkgLists'
kick_set /etc/pacman.conf 'NoExtract' 'etc/pacman.d/mirrorlist'
