#!/usr/bin/env bash

[[ $UID == 0 ]] || { printf "%s\n" "run as root"; exit 1; }
. configuration

do_install openssh

do_set_option /etc/ssh/sshd_config X11Forwarding yes ' '
do_set_option /etc/ssh/sshd_config PermitRootLogin yes ' '

do_enable_service sshd
