#!/usr/bin/env bash

[[ $UID == 0 ]] || { printf "%s\n" "run as root"; exit 1; }
. configuration

do_install sudo
do_write /etc/sudoers.d/disable-logging 'Defaults !syslog, !pam_session'
do_write /etc/sudoers.d/wheel-nopasswd  '%wheel ALL=(ALL) NOPASSWD: ALL'
