#!/usr/bin/env bash

# basic system cli tools

kick_install python python2 htop lsof nano tree psmisc procps-ng util-linux coreutils \
             iotop zip unzip zsh zsh-completions rsync mlocate ncdu pciutils \
             pv sshfs strace unrar progress findutils tmux cryptsetup file git tig \
             grep wget curl aria2 the_silver_searcher gnu-netcat which usbutils gawk \
             tar ack sed bzip2 gzip diffutils patch pkgfile wipe less ranger ps_mem bash \
             source-highlight reflector highlight borg
kick_install_aur utimer wcalc icdiff-git


# file systems

kick_install btrfs-progs dosfstools e2fsprogs f2fs-tools jfsutils ntfs-3g \
             sysfsutils xfsprogs


# network tools

kick_install wireless_tools wol traceroute inetutils iftop iptraf-ng mtr iperf ethtool \
             iputils iw whois bind-tools nethogs net-tools bmon aircrack-ng
