#!/usr/bin/env bash

# basic system cli tools
for p in \
    python python2 htop lsof nano tree psmisc procps-ng util-linux coreutils \
    iotop zip unzip zsh zsh-completions rsync mlocate ncdu pciutils \
    pv sshfs strace unrar progress findutils tmux cryptsetup file \
    grep wget curl aria2 git the_silver_searcher
do
    do_install "$p"
done

# network tools
for p in \
    wol traceroute inetutils iftop iptraf-ng mtr iperf ethtool \
    iputils iw whois bind-tools nethogs net-tools
do
    do_install "$p"
done
