#!/usr/bin/env bash

# sudo
kick_install sudo
kick_write /etc/sudoers.d/disable-logging 'Defaults !syslog, !pam_session'
kick_write /etc/sudoers.d/wheel-nopasswd  '%wheel ALL=(ALL) NOPASSWD: ALL'

# user
kick_useradd "$user"
kick_install zsh
kick_chsh "$user" /bin/zsh
kick_exec usermod -aG wheel "$user"

# dotfiles
kick_install git
target_dir=$(eval echo "~$user/.dotfiles")
kick_clone "https://github.com/a-irs/dotfiles" "$target_dir"
kick_exec su "$user" "$target_dir/.setup.sh"
