#!/usr/bin/env bash

[[ $UID == 0 ]] || { printf "%s\n" "run as root"; exit 1; }
. configuration

do_install xorg-server
do_install xorg-server-utils
do_install xorg-xinit

if lspci | grep -e VGA -e 3D | grep -q Intel; then
    do_install xf86-video-intel
fi
