#!/usr/bin/env bash

kick_install xorg-server
kick_install xorg-server-utils
kick_install xorg-xinit

if lspci | grep -e VGA -e 3D | grep -q Intel; then
    kick_install xf86-video-intel
elif lspci | grep -e VGA -e 3D | grep -q AMD; then
    kick_install xf86-video-ati
    kick_install mesa-vdpau
fi
