#!/usr/bin/env bash

do_install_aur        base-devel
do_install_aur_asdeps package-query
do_install_aur        yaourt

do_set_option /etc/yaourtrc AURSHOWDIFF 1
do_set_option /etc/yaourtrc AURUPGRADE 1
do_set_option /etc/yaourtrc AURUSEGIT 1
do_set_option /etc/yaourtrc EXPORT 2
do_set_option /etc/yaourtrc UP_NOCONFIRM 1
do_set_option /etc/yaourtrc BUILD_NOCONFIRM 1
do_set_option /etc/yaourtrc PU_NOCONFIRM 1
do_set_option /etc/yaourtrc DEVEL 1
do_set_option /etc/yaourtrc DEVELSRCDIR \"/var/cache/yaourt\"
